### example01
GET http://localhost:8080/user/example01

### example02
GET http://localhost:8080/user/example02

### example03
GET http://localhost:8080/user/example03

### example04
GET http://localhost:8080/user/example04

### example05
GET http://localhost:8080/user/example05

### example06
GET http://localhost:8080/user/example06

### example07
GET http://localhost:8080/user/example07

### example08
GET http://localhost:8080/user/example08

### example09
GET http://localhost:8080/user/example09

### example10
GET http://localhost:8080/user/example10