### example01
GET http://localhost:8080/user/1

### example02
GET http://localhost:8080/user/1/TurboWeb/18/true

### example03
GET http://localhost:8080/user/example03?name=TurboWeb&age=18

### example04
POST http://localhost:8080/user/example04
Content-Type: application/x-www-form-urlencoded

name=TurboWeb&age=18

### example05
POST http://localhost:8080/user/example05
Content-Type: application/json

{
  "name": "TurboWeb",
  "age": 18
}

### example06
GET http://localhost:8080/user/example06

### example07
GET http://localhost:8080/user/example07

### example08
GET http://localhost:8080/user/example08

### example09
GET http://localhost:8080/user/example09

### simple01
GET http://localhost:8080/simple01?name=turboweb

### simple02
GET http://localhost:8080/simple02

### simple03
GET http://localhost:8080/simple03?name=turbo&name=web

### simple04
GET http://localhost:8080/simple04?age=18

### simple05
GET http://localhost:8080/simple05?age=19

### simple06
GET http://localhost:8080/simple06?grade=100&grade=99