### example01
GET http://localhost:8080/hello/10

### example02
GET http://localhost:8080/hello/example02/1

### example03
GET http://localhost:8080/hello

### example04
POST http://localhost:8080/hello

### example05
PATCH http://localhost:8080/hello

### example06
PUT http://localhost:8080/hello

### example07
DELETE http://localhost:8080/hello